spring:
  datasource:
    url: jdbc:tc:mysql:8:///
    username: testuser
    password: testpass

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create