spring:
  datasource:
    url: jdbc:tc:mysql:8:///
    username: testuser
    password: testpass
    hikari:
      maximum-pool-size: 40
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create